apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-fact-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-fact-app
  template:
    metadata:
      labels:
        app: bird-fact-app
    spec:
      containers:
      - name: bird-fact-app
        image: ehisakhile/bird-fact-app:1.0.0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: BIRD_FACT_SERVICE_URL
          value: "http://bird-fact-service-svc:4200"
        ports:
        - containerPort: 4201
           
---
apiVersion: v1
kind: Service
metadata:
  name: bird-fact-app-svc
spec:
  selector:
    app: bird-fact-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 4201
      targetPort: 4201
      nodePort: 30001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bird-fact-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird-fact-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15 # App scales when the average utilization exceeds 15%
